name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag harwincu/subnetappgit:v1
    - name: login registry
      run: docker login -u harwin6@hotmail.com -p "Tecnologia2024**"
    - name: push image
      run: docker image push harwincu/subnetappgit:v1
